config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :comments do
    resources :comments
  end
 
  resources :posts do
    resources :comments
  end

  resources :events

  resources :articles
   
  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < Post
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true

  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy

  def post
    return @post if defined?(@post)
    @post = commentable.is_a?(Post) ? commentable : commentable.post
  end
end

app/models/event.rb
class Event < Post
  validates_date :date, on_or_after: lambda { Time.now }
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :body, presence: true
  
  has_many :comments, as: :commentable, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :get_parent
  before_action :authenticate_user!

  def new
    @comment = @parent.comments.new
  end
 
  def create
    @comment = @parent.comments.new(comment_params)
    @comment.user = current_user.email
    if @comment.save
      redirect_to post_path(@comment.post)
    else
      render action: 'new'
    end
  end
 
  protected
   
  def get_parent
    @parent = Post.find_by_id(params[:post_id]) if params[:post_id]
    @parent = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
     
    redirect_to root_path unless defined?(@parent)
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, except: [:show, :index]
  before_action :require_permission, only: [:edit, :destroy]
  
  def index
    @posts = Post.order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user.email
    if @post.save then
      redirect_to @post
    else
      render action: 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render action: 'edit'
    end
  end

  def destroy
    Post.find(params[:id]).destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def require_permission
    post = Post.find(params[:id])
    if post.user != current_user.email
      flash[:alert] = 'Only the user who created the post, can delete or edit it'
      redirect_to post
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<li class='comment'>
	<small>written by <%= comment.user %> at <%= comment.created_at %></small><br>
	<%= comment.body %><br>
	<%= link_to '>>> Add a reply', new_comment_comment_path(comment), class: 'btn btn-default btn-xs' %>
	<% unless comment.comments.empty? %>
		<ul class="comment_list">
	 		<%= render(partial: 'comments/comment', collection: comment.comments) %>
		</ul>
	<% end %>
</li>

app/views/comments/_form.html.erb
<%= form_for [parent, comment] do |f| %>
	<% if comment.errors.any? %>
		<h3 class='row'><%= pluralize(comment.errors.count, "error") %></h3>
		<%= render(partial: 'layouts/alert', collection: comment.errors.full_messages) %>
	<% end %>

	<div class='row'>
		<%= f.text_area :body, class: 'col-sm-12' %>
	</div>
	<br>
	<div class='row'>
		<%= f.submit class: 'btn btn-default' %>
	</div>
<% end %>

app/views/comments/new.html.erb
<h2>Add a comment:</h2>
<%= render(partial: 'form', locals: { parent: @parent, comment: @comment }) %>

app/views/layouts/_alert.erb
<div class="row">
	<div class="col-xs-12">
	  <div class="alert alert-warning fade in">
	    <a href="#" class="close" data-dismiss="alert">&times;</a>
	    <span class="glyphicon glyphicon-exclamation-sign"></span>
	    <%= alert %>
	  </div>
	</div>
</div>

app/views/layouts/_notice.erb
<div class="row">
	<div class="col-xs-12">
	  <div class="alert alert-info fade in">
	    <a href="#" class="close" data-dismiss="alert">&times;</a>
	    <span class="glyphicon glyphicon-info-sign"></span>
	    <%= notice %>
	  </div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogWithNestedComments</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>

  <body>
  	<div class="container">

		<nav class="navbar navbar-default navbar-fixed-top">
		    <div class="container">
		      <div class="navbar-header">
		        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
		          <span class="sr-only">Toggle navigation</span>
		          <span class="icon-bar"></span>
		          <span class="icon-bar"></span>
		          <span class="icon-bar"></span>
		        </button>
		        <a class="navbar-brand" href="/">Blog</a>
		      </div>

		      <div class="navbar-collapse collapse">
		        <ul class="nav navbar-nav">
		        	<li><%= link_to "Show all posts", posts_path %>
		        </ul>
		        <ul class="nav navbar-nav navbar-right">
		        	<% if user_signed_in? %>
						<p class="navbar-text">User: <%= current_user.email %></p>
						<li><%= link_to "Log Out", destroy_user_session_path, method: :delete %>
					<% else %>
						<li><%= link_to "Log In", new_user_session_path %>
					<% end %>
		        </ul>
		      </div>
		    </div>
		</nav>
		
		<% if flash[:alert] %>
			<%= render(partial: 'layouts/alert', object: flash[:alert]) %>
		<% end %>

		<% if flash[:notice] %>
			<%= render(partial: 'layouts/notice', object: flash[:notice]) %>
		<% end %>

		<%= yield %>
	</div>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_comment.html.erb
<div>
  <%= comment.body %>
</div>

<p><%= link_to '>>> Add a Reply', new_comment_comment_path(comment) %></p>
   
<% unless comment.comments.empty? %>
  <ul class="comment_list">
    <%= render(partial: 'comment', collection: comment.comments) %>
  </ul>
<% end %>

app/views/posts/_form.html.erb
<%= form_for post do |f| %>
	<% if post.errors.any? %>
		<h3 class='row'><%= pluralize(post.errors.count, "error") %></h3>
		<%= render(partial: 'layouts/alert', collection: post.errors.full_messages) %>
	<% end %>

	<br>
	<div class='row'>
		<%= f.label :title %><br>
		<%= f.text_field :title, class: 'col-sm-12' %>
	</div>
	<br>
	<div class='row'>
		<%= f.label :body %><br>
		<%= f.text_area :body, class: 'col-sm-12' %>
	</div>
	<br>
	<div class='row'>
		<%= f.submit class: 'btn btn-default' %>
	</div>

<% end %>

<!-- REMOVE THIS LATE!!! -->
<script type="text/javascript">window.onload = kindCheck();</script>

app/views/posts/_post.html.erb
<article>
	<div class='row'>
		<h3><%= link_to post.title, post_path(post) %>
		<%= " start at: #{post.date}" if post.kind=='event' %></h3>
		<small>posted <%= post.user %> at <%= post.created_at %> <% if post.created_at!=post.updated_at %>/ updated at <%= post.updated_at %><% end %></small>
		<p><%= simple_format(truncate_size ? post.body.truncate(truncate_size) : post.body) %></p>
		<hr>
	</div>
</article>

app/views/posts/edit.html.erb
<h3>Edit post</h3>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<h2 class='row'>List of posts</h2>
<div class='row'>
	<%= link_to ">>> Create new post <<<", new_post_path, class: 'btn btn-default' %>
</div>
<%= render(partial: "post", collection: @posts, locals: { truncate_size: 120}) %>

app/views/posts/new.html.erb
<h3 class='row'>Add new post</h3>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<%= render(partial: "post", object: @post, locals: { truncate_size: nil}) %>
<div class='row'>
	<%= link_to ">>> Edit", edit_post_path, class: 'btn btn-default' %>
	<%= link_to "Delete <<<", post_path, method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-danger' %>
</div>
<hr class='row'>
<h4 class='row'>Comments:</h4>
<ul class="comment_list">
	<%= render(partial: 'comments/comment', collection: @post.comments) %>
</ul>
<hr class='row'>
<h4 class='row'>Add a comment:</h4>
<%= render(partial: 'comments/form', locals: { parent: @post, comment: @post.comments.build }) %>